### ISSUE TITLE
GD-21: Option to change working-directory

### ISSUE THREAD

**Issue by kdavis** [MikeSchulze/gdUnit4-action#21]
**Is your feature request related to a problem? Please describe.**
I'm trying to change working-directory as my Godot project lives under the "src" folder, but I'm encountering a few issues when trying a few things

**Describe the solution you'd like**

```yaml
    - uses: MikeSchulze/gdUnit4-action@v1.0.4
      name: gdUnit Test Runner
      with:
        godot-version: '4.2.1'
        godot-status: 'stable'
        working-directory: src
```

**Describe alternatives you've considered**
I tried using the `paths` property, but 
- if the csproj can't be found, I get `MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.`
- if the godot project is in another folder, it redownloads the gdUnit assets because of https://github.com/MikeSchulze/gdUnit4-action/blob/master/action.yml#L90 (and if I specify "installed", it will use the root `addons/gdUnit4` folder)
