### ISSUE TITLE
Optional Report Upload/Publishing

### ISSUE THREAD

**Issue by kdavis** [MikeSchulze/gdUnit4-action#23]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to disable the publishing of artifacts for the test runner, but still have the tests run to see a pass/fail. 

**Describe the solution you'd like**
A property in the `with` section, like "upload-report" which takes a true/false (or optionally, a github var like `${{ github.event.pull_request.draft == false }}`
```
    - uses: MikeSchulze/gdUnit4-action@v1
      with:
        godot-version: '4.2.1'
        godot-status: 'stable'
        upload-report: false
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
