### ISSUE TITLE
GD-45: The action do cache the wrong godot version when set `godot-force-mono : 'true'`

### ISSUE THREAD

**Issue by MikeSchulze** [MikeSchulze/gdUnit4-action#45]
### The used gdUnit4-action version

gdUnit4-action@v1.0.3 (Latest Release)

### The used Godot version

all

### Operating System

all

### Describe the bug

To run GDScript tests with Godot mono version, you can set the parameter ` godot-force-mono` to true.
But this results into a wrong action cache, it stores the standard Godot version under the mono cache.

```yml
      - name: 'Test gdUnit4-action: force run Godot Mono'
        id: test-force-mono
        timeout-minutes: 5
        uses: ./
        with:
          godot-version: 4.2.2
          godot-force-mono : 'true'
          paths: |
            res://tests/
          timeout: 2
          report-name: gdUnit4-force-mono
```
