### ISSUE TITLE
Unexpected input 'publish-report' warning during post job cleanup

### ISSUE THREAD

**Issue by knightofiam** [MikeSchulze/gdUnit4-action#49]
### The used gdUnit4-action version

gdUnit4-action@v1

### The used Godot version

v4.3.dev6

### Operating System

ubuntu:latest

### Describe the bug

According to the README, `publish-report` is a valid option, and needs to be set to `false` for forked pull requests. The run still completes successfully.

Relevant yaml snippet:
```
      # Run the tests in res://test/unit & generate test-results.xml report
      # with a unique name that includes the run ID & branch name to clearly
      # identify & distinguish between multiple test report files.
      - name: Setup GdUnit4 and run tests
        uses: MikeSchulze/gdUnit4-action@v1
        with:
          godot-version: '4.3'
          godot-status: 'dev6'
          paths: 'res://test/unit'
          publish-report: ${{ env.PUBLISH_REPORT }}
          # If we're on a fork, the report will be uploaded as an artifact named "artifact_<report_name>"
          report-name: 'test-results-${{ github.run_id }}-${{ env.SANITIZED_REF_NAME }}.xml'
```

Relevant log snippet:
```
Warning: Unexpected input(s) 'publish-report', valid inputs are ['godot-version', 'godot-status', 'godot-net', 'version', 'paths', 'arguments', 'timeout', 'retries', 'report-name']
Post job cleanup.
Post job cleanup.
Cache hit occurred on the primary key Linux-Godot_v4.3-dev6, not saving cache.
```
