### ISSUE TITLE
Add option to treat warnings as errors

### ISSUE THREAD

**Issue by MikeSchulze** [MikeSchulze/gdUnit4-action#61]
**Is your feature request related to a problem? Please describe.**
The test tool has return codes defined as:
```
	const RETURN_SUCCESS = 0
	const RETURN_ERROR = 100
	const RETURN_ERROR_HEADLESS_NOT_SUPPORTED = 103
	const RETURN_ERROR_GODOT_VERSION_NOT_SUPPORTED = 104
	const RETURN_WARNING = 101
```

The action do not well handle the codes:
```
  if (exitCode !== 0) {
      core.setFailed(`The tests was failed after ${retries} retries with exit code: ${exitCode}`);
    } else if (retriesCount > 0 && retries > 0) {
      core.warning(`The tests was successfully after ${retriesCount} retries with exit code: ${exitCode}`);
    }
```

**Describe the solution you'd like**
The action should provide a new option `warnings-as-errors` to control the action ends with warning or error.
```
  warnings-as-errors:
    description: 'Treat test warnings as errors (return code 101 will be treated as error)'
    required: false
    default: 'false'
```

**Describe alternatives you've considered**
n/a

**Additional context**
