### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by knightofiam** [MikeSchulze/gdUnit4-action#66]
### The used gdUnit4-action version

gdUnit4-action@v1.1.1

### The used Godot version

4.3.stable.mono

### Operating System

macOS Sonoma (14.5)

### Describe the bug

Relevant log excerpt:
```
Debugger Break, Reason: 'Parser Error: Identifier "GdUnitTestResourceLoader" not declared in the current scope.'
*Frame 0 - res://addons/gdUnit4/src/core/GdUnitTestSuiteScanner.gd:207 in function ''
Enter "help" for assistance.
debug> Segmentation fault (core dumped)
Run tests ends with 139
```

This behavior started within the last 2 weeks.

Relevant build file excerpt, keeping in mind this worked several weeks ago, and I haven't changed it since:

```yml
# Run the tests in res://test/unit & generate test-results.xml report
# with a unique name that includes the run ID & branch name to clearly
# identify & distinguish between multiple test report files.
- name: Setup GdUnit4 and run tests
  # Using '@v1' won't use the latest version, so specify explicit version.
  uses: MikeSchulze/gdUnit4-action@v1.1.1
  with:
    godot-version: '4.3'
    godot-status: 'stable'
    godot-net: false # Don't run only C# tests.
    godot-force-mono: true # Run both C# & GDScript tests using the Mono engine.
    version: 'master'
    paths: 'res://tests'
    retries: 3
    publish-report: ${{ env.PUBLISH_REPORT }}
    # If we're on a fork, the report will be uploaded as an artifact named "artifact_<report_name>"
    report-name: 'test-results-${{ github.run_id }}-${{ env.SANITIZED_REF_NAME }}.xml'
```
